//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsOnlineShop
    {
        public int ID { get; set; }
        public string OnlineShopName { get; set; }
        public Nullable<bool> OnlineShopLogo { get; set; }
        public string PhoneNumber { get; set; }
        public string UserID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
